apiVersion: 1

datasources:
  - name: Prometheus              # Имя источника в Grafana
    type: prometheus              # Тип — Prometheus
    url: http://prometheus:9090   # Адрес Prometheus внутри Docker-сети
    isDefault: true               # Использовать по умолчанию
    uid: prometheus               # Уникальный ID для ссылок из дашбордов